name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^3.1.2
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^6.1.5
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.3.6
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^12.0.1
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-1.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app-icon-1.jpeg"

flutter_native_splash:
  color: "#252829"
  image: assets/icon/app-icon-2.png

  android_12:
    color: "#252829"
    image: assets/icon/app-icon-2.png


flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/loaders/
